---
name: MarkdownLint

on:
  push:
  pull_request:
    branches: [master, main]

#env:

concurrency:
  # https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          config: ".markdownlint.yaml"
          globs: "**/*.md"

